config/routes.rb
Rails.application.routes.draw do

  resources :adress_informations

  resources :age_ranges

  get 'users/show'

  resources :genders

  resources :bank_informations

  resources :categories

  scope "(:locale)", locale: /en|tr/ do
    devise_for :users, controllers: { registrations: "registrations" }
    resources :users, :only => [:show] do
      resources :reviews, except: [:show, :index]
    end
    
    resources :listings do
      resources :orders, only: [:create, :new]
    end

    match 'about' => 'pages#about', via: [:get]
    get  'contact' => 'pages#contact'
    get 'seller' => "listings#seller"
    get 'sales' => "orders#sales"
    get 'purchases' => "orders#purchases"
    
    root 'listings#index'
  end
 

end

app/models/listing.rb
class Listing < ActiveRecord::Base  
   if Rails.env.development?
	has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
   else
	has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg"
    #:storage => :dropbox,
    #:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
  	#:path => ":style/:id_:filename"
 	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
   end

   validates :name, :description, :price, presence: true
   validates :price, numericality: {greater_than: 0} 
   validates_attachment :image, :presence => true,
  :size => { :in => 0..2.megabytes }

  belongs_to :user
  accepts_nested_attributes_for :user
  has_many :orders
  has_many :pictures, dependent: :destroy
  belongs_to :category
  belongs_to :gender
  belongs_to :age_range

  def to_param
    "#{id}-#{name.parameterize}"
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end 
 
  # GET /listings
  # GET /listings.json
  def index
    find_listing

    if (params[:category].blank?) && (params[:gender].blank?)
      @listings ||= Listing.all.order("created_at DESC")
      @listings = @listings.paginate(:page => params[:page], :per_page => 12)
    else
      @category_id = Category.find_by(name: params[:category]).try(:id)
      
      @listings = Listing.where(category_id: @category_id)
      if params[:gender].present?
        @gender_id = Gender.find_by(name: params[:gender]).id rescue ''
        @listings = @listings.where(gender_id: @gender_id)
      end
      @listings = @listings.paginate(:page => params.fetch(:page, 1), :per_page => 12)
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
     @listing = current_user.listings.build
     @listing.user.build_bank_information unless current_user.has_bank_information?
     @listing.user.build_adress_information unless current_user.has_adress?
  end
 
  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
      
      @listing = Listing.new(listing_params)
      
      @listing.user_id = current_user.id

      @listing.save 

      unless bank_account_params.blank?
        @bank_information_data = bank_account_params
        @bank_info = BankInformation.new(@bank_information_data['user_attributes']['bank_information_attributes'])
        @bank_info.user_id =  current_user.id
        @bank_info.save
      end

      unless adress_field_params.blank?
        @adress_information_data = adress_field_params
        puts adress_field_params
        #debugger
        @adress_info = AdressInformation.new(@adress_information_data['user_attributes']['adress_information_attributes'])
        @adress_info.user_id = current_user.id
        @adress_info.save
      end
    

   # if current_user.recipient.blank?
   #   Stripe.api_key = ENV["STRIPE_API_KEY"]
   #   token = params[:stripeToken]

    #  recipient = Stripe::Recipient.create(
    #    :name => current_user.name,
    #    :type => "individual",
    #    :bank_account => token
    #    )

    #  current_user.recipient = recipient.id
    #  current_user.save
    #end

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def find_listing
     conditions = []
     conditions << "listings.name LIKE '%#{params[:name]}%'" if params[:name].present?
     conditions << "listings.description LIKE '%#{params[:description]}%'" if params[:description].present?
     @listings = Listing.where(conditions.join(" AND ")).order("listings.name" || "listings.description")

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:id, :name, :description, :price, :image, :category_id, :product_condition, :gender_id, :age_range, :delivery_information)
    end

    def bank_account_params
      params.require(:listing).permit(user_attributes: [ :id, bank_information_attributes: [:id, :bank_account, :bank_name] ])
    end

    def adress_field_params
      params.require(:listing).permit(user_attributes: [:id, adress_information_attributes: [:id, :adress, :postal_code, :city, :cell_phone] ])
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation", class= "alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 

  <div id="stripe_error" class="alert alert-danger" style="display:none">
        <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>

  <div class="form-group">
    <%= f.label :name, "Başlık" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Tanıtım" %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price, "Fiyat" %><br>
    <%= f.text_field :price, class: "form-control", value:"444" %>
  </div>
  <div class="form-group">
    <%= f.label :image, "Resim" %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category_id, "Kategorini Seç" %><br>
     <%= f.collection_select :category_id, Category.all, :id , :name, {prompt: "Lütfen Kategori Seçiniz"}, {class: "btn btn-default dropdown-toggle"}  %>  
  </div>
  <div class="form-group">
    <%= f.label :product_condition, "Ürünün Durumu" %><br>
    <%= f.select :product_condition, options_for_select([:yeni, :az_kullanilmis, :kullanilmis]), { :prompt => "Lütfen Seçiniz"}, {class: "btn btn-default dropdown-toggle"}  %>
  </div>
  <div class="form-group">
    <%= f.label :gender_id, "Cinsiyet Seç" %><br>
    <%= f.collection_select :gender_id, Gender.all, :id , :name, {prompt: "Lütfen Cinsiyet Seçiniz"}, {class: "btn btn-default dropdown-toggle"}  %>
  </div>
   <div class="form-group">
    <%= f.label :age_range_id, "Yaş Aralığı Seç" %><br>
     <%= f.collection_select :age_range_id, AgeRange.all, :id , :age, {prompt: "Lütfen Yaş Aralığı Seçiniz"}, {class: "btn btn-default dropdown-toggle"}  %>  
  </div>
  <div class="form-group">
    <%= f.label :delivery_information, "Gönderim Türü" %><br>
    <%= f.select :delivery_information, options_for_select(["Sadece Elden Teslim", "Sadece Kargolanır", "Elden Teslim ya da Kargolanır"]), { :prompt => "Lütfen Seçiniz"}, {class: "btn btn-default dropdown-toggle"} %>
  </div>
  <br>
    <% unless current_user.has_adress? %>
    <%= f.fields_for :user do |u| %>
       <%= u.fields_for :adress_information do |b| %>
           <%= b.label :adress %>
           <%= b.text_field :adress %>
           <%= b.label :city %>
           <%= b.text_field :city %>
           <%= b.label :postal_code %>
           <%= b.text_field :postal_code %>
           <%= b.label :cell_phone %>
           <%= b.text_field :cell_phone %>
       <% end %>
     <% end %>
     <% end %>

  <%#<% if current_user.(bank_name && bank_account).blank? %>
  <!--<h3>Banka Hesap Bilgiler</h3>
    <div class="form-group">
  <%#    <%= f.label :bank_name, "Banka Adı" %><br>
  <%#    <%= f.text_field :bank_name, class: "form-control" %>
    </div>

    <div class="form-group">
   <%#   <%= f.label :bank_account, "Banka Iban Numarası" %><br>
   <%#   <%= f.text_field :bank_account, class: "form-control" %>
    </div>
    <%#<% end %> banka bilgileri -->

    <% unless current_user.has_bank_information? %>
    <%= f.fields_for :user do |u| %>
       <%= u.fields_for :bank_information do |b| %>
           <%= b.label :bank_name %>
           <%= b.text_field :bank_name %>
           <%= b.label :bank_account %>
           <%= b.text_field :bank_account %><br>
      
           <em>Not 1:Üyelik ad ve soyadınız, vereceğiniz banka bilgisindeki ad soyad ile aynı olmalı. Farklı ise lütfen Profilim sayfasından düzeltiniz.</em><br>
           <em>Elden teslim secilmis ise banka bilgilerini girmesine gerek yok.</em><br>
           <em>Uyelik sozlesmesini, Mesafeli satis sozlesmesini checkbox latmamiz lazim.</em><br>
           <em>Saticinin Alici adres bilgisine ulasmasi icin, Satislarim bolumundeki tabloya alicinin adresini ekle.</em><br>
           <em>Uye guncellemede banka bilgileri textbox inida gir.</em><br>
           <em>Saticiya urunu satildiktan sonra email atilmali</em><br>
           <em>Saticinin email atildiktan sonra en gec 3 is gunu icinde kargo sirketi adi ve takip noyu sitede dump girmesi lazim. Alicinin da o noyu gormesi gerekli satin aldiklarim bolumunden.</em><br>
           <em>SSS de ve urun listeleme sayfasinda kargo ucretinin alicinin odemesi gerektigini, eger kusur varsa iade ucretinin saticiya ait oldugunu yazmamiz gerekli. Ya da listelenecek urun yaratilirken comboboxta odeme tercihi girilmelidir. Sadece Kargolanir(Odeme Alıcıya aittir) gibi</em><br>
           <em>Satici urunun kargo nosunu yazdiktan 4 is gunu sonra aliciya mail atilmali. Urun alindiysa satin aldiklarim tablosunda elime gecti butonuna basmali. Bastiktan sonra sadece bana teslim alindi maili atilip, ben de ucreti saticiya gonderirim.</em><br>
           <em>Alici, elime gecti butonuna bastiktan sonra satici user'ina review birakma yetkisine sahip olabilir</em><br>
           <em>Ürün hakkinda yorumu da eklemeliyiz</em><br>
           <em>Urun bazinda facebook like</em><br>
           <em>Kullanici adi(username) eklenmeli</em><br>
           <em>Urun satinca listeleme sayfasindan cikmali o urun</em><br>
           <em>Urunu listelemeden once adminden onay verilmesi gerekli. Onay verildikten sonra listeleme sayfasinda listelenmeli.</em>
       <% end %>
    <% end %>
    <% end %>

 <!--<%# <% if current_user.recipient.blank? %>
  <h1>Bank Account Information</h1>
    <div class= "form-group">
<%#      <%= label_tag :country %>
<%#      <%= text_field :country, nil, { :name => nil, :'data-stripe' => "country", class: "form-control" } %>
    </div>

      <div class= "form-group">
<%#      <%= label_tag :routing_number %>
<%#      <%= text_field :routing_number, nil, { :name => nil, :'data-stripe' => "routingNumber", class: "form-control" } %>
    </div>

      <div class= "form-group">
<%#      <%= label_tag :account_number %>
<%#      <%= text_field :account_number, nil, { :name => nil, :'data-stripe' => "accountNumber", class: "form-control" } %>
    </div>
<%#  <% end %> Stripe Bank account info--> 

    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<%# <div class= "pull-right">
  <div class="fb-like" data-href="http://etsydemo-surferalp.herokuapp.com" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false">
  </div>
</div>
<br><br>  flikebutton %>

  <%= render '/layouts/carousel' %>

  <br><br>
  <%= form_tag "", class: "form-horizontal", method: :get do %>
    
    <div class="form-group">
      <%= label_tag :name, "Arama", class: "control-label col-md-6" %>

      <div class="col-md-4">
        <%= text_field_tag :name, (params[:name].present?) ? params[:name] : "", class: "form-control", placeholder: "Arama" %>
      </div>
    
      <div class="form-group">
        <div class="col-md-2">
          <%= submit_tag "Filtrele", class: "btn btn-default" %>
        </div>
    </div>
  <% end %>

<div class= "center">
<div class="row">
  <% @listings.each do |listing| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag(listing.image.url), listing %>
        <div class="caption">
         <h3><%= listing.name %></h3>
         <p><%= number_to_currency(listing.price) %></p>
         <p><%= t('sold_by', user: listing.user.name) %></p>
        </div>
      </div>
     </div>
    <% end %>
  </div>
</div>
<br>

<div class= "center">
<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

<br>
<% if (user_signed_in?) %>
  <%= link_to new_listing_path, class: "btn btn-primary", data: { no_turbolink: true } do %>
  <i class= "glyphicon glyphicon-plus"></i><%= t('new_listing') %>
  <% end %>
<% else %>
  <%= link_to new_user_registration_path, class: "btn btn-primary" do %>
  <i class= "glyphicon glyphicon-plus"></i><%= t('new_listing') %>
  <% end %>
<% end %>

  <div class="center">
    <div class="fb-like" data-href="https://karlibebek.com" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
  </div>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/seller.html.erb
<table class= "table table-striped table-bordered">
	<tr>
		<th class="center">Image</th>
		<th class="center">Name</th>
		<th class="center">Description</th>
		<th class="center">Price</th>
		<th class="center">Action</th>
	</tr>

	<% @listings.each do |listing| %>
	<tr>
		<td class="center"><%= image_tag listing.image.url(:thumb) %></td>
		<td><%= listing.name %></td>
		<td><%= listing.description %></td>
		<td><%= number_to_currency(listing.price) %></td>
		<td>
		 <div class="btn-group">
			  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
			    Action <span class="caret"></span>
			  </button>
			  <ul class="dropdown-menu" role="menu">
			    <li><%= link_to "View", listing, class: "btn btn-link" %></li>
			    <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
			    <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
			    </li>
			  </ul>
		 </div>
		</td>
	</tr>
	<% end %>
</table>

<br>
<% if (user_signed_in?) %>
  <%= link_to 'New Listing', new_listing_path, class: "btn-link", data: { no_turbolink: true } %>
<% else %>
  <%= link_to 'New Listing', new_user_session_path, class: "btn-link", data: { no_turbolink: true } %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
	<%= image_tag @listing.image.url %>
		</div>
	</div>
	<div class="col-md-6">
		<h3><%= @listing.name %></h3>
		<p><%= number_to_currency(@listing.price) %></p>
		<p><%= @listing.description %></p>
		<br>
		<div class = "center">
		   <%= link_to 'Buy It Now', new_listing_order_path(@listing), class: "btn btn-primary", data: { no_turbolink: true } %> 
	    </div>
	</div>
</div>

<% if current_user == @listing.user %>
<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> 
<% end %>
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

<div class="center">
    <div class="fb-like" data-href="<?=$current_url?>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
  </div>