config/routes.rb
Rails.application.routes.draw do

  resources :adress_informations

  resources :age_ranges

  get 'users/show'

  resources :genders

  resources :bank_informations

  resources :categories

  scope "(:locale)", locale: /en|tr/ do
    devise_for :users, controllers: { registrations: "registrations" }
    resources :users, :only => [:show] do
      resources :reviews, except: [:show, :index]
    end
    
    resources :listings do
      resources :orders, only: [:create, :new]
    end

    match 'about' => 'pages#about', via: [:get]
    get  'contact' => 'pages#contact'
    get 'seller' => "listings#seller"
    get 'sales' => "orders#sales"
    get 'purchases' => "orders#purchases"
    
    root 'listings#index'
  end
 

end

app/models/bank_information.rb
class BankInformation < ActiveRecord::Base
	belongs_to :user
end

app/controllers/bank_informations_controller.rb
class BankInformationsController < ApplicationController
  before_action :set_bank_information, only: [:show, :edit, :update, :destroy]

  # GET /bank_informations
  # GET /bank_informations.json
  def index
    @bank_informations = BankInformation.all
  end

  # GET /bank_informations/1
  # GET /bank_informations/1.json
  def show
  end

  # GET /bank_informations/new
  def new
    @bank_information = BankInformation.new
  end

  # GET /bank_informations/1/edit
  def edit
  end

  # POST /bank_informations
  # POST /bank_informations.json
  def create
    @bank_information = BankInformation.new(bank_information_params)

    respond_to do |format|
      if @bank_information.save
        format.html { redirect_to @bank_information, notice: 'Bank information was successfully created.' }
        format.json { render :show, status: :created, location: @bank_information }
      else
        format.html { render :new }
        format.json { render json: @bank_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_informations/1
  # PATCH/PUT /bank_informations/1.json
  def update
    respond_to do |format|
      if @bank_information.update(bank_information_params)
        format.html { redirect_to @bank_information, notice: 'Bank information was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_information }
      else
        format.html { render :edit }
        format.json { render json: @bank_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_informations/1
  # DELETE /bank_informations/1.json
  def destroy
    @bank_information.destroy
    respond_to do |format|
      format.html { redirect_to bank_informations_url, notice: 'Bank information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_information
      @bank_information = BankInformation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_information_params
      params.require(:bank_information).permit(:bank_name, :bank_account, :user_id, :listing_id)
    end
end

app/helpers/bank_informations_helper.rb
module BankInformationsHelper
end

app/views/bank_informations/_form.html.erb
<%= form_for(@bank_information) do |f| %>
  <% if @bank_information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank_information.errors.count, "error") %> prohibited this bank_information from being saved:</h2>

      <ul>
      <% @bank_information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bank_name %><br>
    <%= f.text_field :bank_name %>
  </div>
  <div class="field">
    <%= f.label :bank_account %><br>
    <%= f.number_field :bank_account %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bank_informations/edit.html.erb
<h1>Editing bank_information</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank_information %> |
<%= link_to 'Back', bank_informations_path %>

app/views/bank_informations/index.html.erb
<h1>Listing bank_informations</h1>

<table>
  <thead>
    <tr>
      <th>Bank name</th>
      <th>Bank account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bank_informations.each do |bank_information| %>
      <tr>
        <td><%= bank_information.bank_name %></td>
        <td><%= bank_information.bank_account %></td>
        <td><%= link_to 'Show', bank_information %></td>
        <td><%= link_to 'Edit', edit_bank_information_path(bank_information) %></td>
        <td><%= link_to 'Destroy', bank_information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank information', new_bank_information_path %>

app/views/bank_informations/new.html.erb
<h1>New bank_information</h1>

<%= render 'form' %>

<%= link_to 'Back', bank_informations_path %>

app/views/bank_informations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bank name:</strong>
  <%= @bank_information.bank_name %>
</p>

<p>
  <strong>Bank account:</strong>
  <%= @bank_information.bank_account %>
</p>

<%= link_to 'Edit', edit_bank_information_path(@bank_information) %> |
<%= link_to 'Back', bank_informations_path %>