config/routes.rb
Rails.application.routes.draw do

  resources :adress_informations

  resources :age_ranges

  get 'users/show'

  resources :genders

  resources :bank_informations

  resources :categories

  scope "(:locale)", locale: /en|tr/ do
    devise_for :users, controllers: { registrations: "registrations" }
    resources :users, :only => [:show] do
      resources :reviews, except: [:show, :index]
    end
    
    resources :listings do
      resources :orders, only: [:create, :new]
    end

    match 'about' => 'pages#about', via: [:get]
    get  'contact' => 'pages#contact'
    get 'seller' => "listings#seller"
    get 'sales' => "orders#sales"
    get 'purchases' => "orders#purchases"
    
    root 'listings#index'
  end
 

end

app/models/adress_information.rb
class AdressInformation < ActiveRecord::Base
	belongs_to :user
end

app/models/age_range.rb
class AgeRange < ActiveRecord::Base
	has_many :listings
end

app/models/bank_information.rb
class BankInformation < ActiveRecord::Base
	belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :listings
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/gender.rb
class Gender < ActiveRecord::Base
	has_many :listings
end

app/models/listing.rb
class Listing < ActiveRecord::Base  
   if Rails.env.development?
	has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
   else
	has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg"
    #:storage => :dropbox,
    #:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
  	#:path => ":style/:id_:filename"
 	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
   end

   validates :name, :description, :price, presence: true
   validates :price, numericality: {greater_than: 0} 
   validates_attachment :image, :presence => true,
  :size => { :in => 0..2.megabytes }

  belongs_to :user
  accepts_nested_attributes_for :user
  has_many :orders
  has_many :pictures, dependent: :destroy
  belongs_to :category
  belongs_to :gender
  belongs_to :age_range

  def to_param
    "#{id}-#{name.parameterize}"
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
	#validates :adress, :city, :state, presence: true

	belongs_to :listing
	belongs_to :buyer, class_name: "User"
	belongs_to :seller, class_name: "User"
end

app/models/picture.rb
class Picture < ActiveRecord::Base

belongs_to :listing
if Rails.env.development?
	has_attached_file :image, :styles => { :medium => "15x", :thumb => "10x10>" }, :default_url => "default.jpg"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
   else
	has_attached_file :image, :styles => { :medium => "15x", :thumb => "10x10>" }, :default_url => "default.jpg"
    #:storage => :dropbox,
    #:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
  	#:path => ":style/:id_:filename"
 	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
   end

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user, class_name: "User"
	belongs_to :author, class_name: "User"

	validates :rating, :comment, presence: true
	validates :rating, numericality: {
		only_integer: true,
		greater_then_or_equal_to: 1,
		less_than_or_equal_to: 5,
		message: "Değerlendirme sadece 1 ile 5 arasında ve tam sayı olarak yapılır."
	}

end

app/models/user.rb
class User < ActiveRecord::Base
	if Rails.env.development?
	has_attached_file :image, :styles => { :medium => "100x", :thumb => "30x30>" }, :default_url => "default.jpg"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
   else
	has_attached_file :image, :styles => { :medium => "100x", :thumb => "30x30>" }, :default_url => "default.jpg"
    #:storage => :dropbox,
    #:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
  	#:path => ":style/:id_:filename"
 	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
   end

   validates_attachment :image, :presence => true,
   :size => { :in => 0..1.megabytes }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         validates :name, presence: true 
         validates :user_name, presence: true 

  has_many :listings, dependent: :destroy
  has_one :bank_information, dependent: :destroy
  has_many :reviews, dependent: :destroy
  accepts_nested_attributes_for :bank_information
  has_one :adress_information, dependent: :destroy
  accepts_nested_attributes_for :adress_information
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"


  def self.can_review? (buyer, seller)
    Order.where(buyer_id: buyer.id, seller_id: seller.id).any?
  end

  def has_adress?
    AdressInformation.where(user_id: id).any?
  end

  def has_bank_information?
    BankInformation.where(user_id: id).any?
  end


end

app/helpers/age_ranges_helper.rb
module AgeRangesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
		return '' if resource.errors.empty?

		messages = resource.errors.full_messages.map {|msg| content_tag(:li, msg) }.join
		sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

		html = <<-HTML 

		<div class=" alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<h4>#{sentence}</h4>
			#{messages}
		</div>
		HTML

		html.html_safe
	end
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_carousel.html.erb
<div class="banner">

      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
             <%= link_to image_tag("https://s3.amazonaws.com/karlibebek/carousel/IMG_8167.JPG") %>
            <div class="carousel-caption">
              <h2>HTML is my Beach House</h2>
            </div>
          </div>
          <div class="item">
             <%= link_to image_tag("https://s3.amazonaws.com/karlibebek/carousel/IMG_8150.JPG") %>
            <div class="carousel-caption">
              <h2>CSS is where I meet my Friends</h2>
            </div>
          </div>
          <div class="item">
             <%= link_to image_tag("https://s3.amazonaws.com/karlibebek/carousel/IMG_8033.JPG") %>
            <div class="carousel-caption">
                <h2>JavaScript is my Hot Hot Tea</h2>
            </div>
          </div>
        </div><!-- .carousel-inner --> 

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div><!-- .carousel --> 
    </div><!-- .banner --> 

app/views/layouts/_facebook.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/tr_TR/sdk.js#xfbml=1&appId=415517888586576&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script> 

app/views/layouts/_footer.html.erb
<div class= "navbar navbar-default">
	<br>
	<strong><em>Copyright 2014</em></strong>
</div>

app/views/layouts/_header.html.erb
	<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Karlı Bebek", root_path, class: "navbar-brand" %>
  </div>
  
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to t('navbar.hakkımızda'), about_path %></li>
       
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('navbar.kategoriler') %> <b class=" caret"></b></a> 
          <ul class="dropdown-menu">
              <% Category.all.each do |category| %>
              <li><%= link_to category.name, listings_path(category: category.name) %></li>
               <% end %>
          </ul>
        </li> 

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('navbar.cinsiyete_göre') %> <b class=" caret"></b></a>
          <ul class="dropdown-menu">
              <% Gender.all.each do |gender| %>
              <li><%= link_to gender.name, listings_path(gender: gender.name) %></li>
               <% end %>
          </ul>
        </li> 
              
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('navbar.yaş_aralığına_göre') %> <b class=" caret"></b></a>
          <ul class="dropdown-menu">
              <% AgeRange.all.each do |agerange| %>
              <li><%= link_to agerange.age, listings_path(agerange: agerange.age) %></li>
               <% end %>
          </ul>
        </li>     
           
        


      <!-- <li class="dropdown">
       <%# <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('navbar.language') %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
         <%# <li><%= link_to t('navbar.english'), root_path(locale: 'en') %></li>
         <%# <li><%= link_to t('navbar.turkish'), root_path(locale: 'tr') %></li>
        </ul>
      </li> -->
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      </li>
          <li class="group">
        <%= image_tag current_user.image.url(:medium) %>
          </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('navbar.satıcı_hesabım') %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to t('navbar.listeni_yönet'), seller_path %></li>
            <li><%= link_to t('navbar.satışlarım'), sales_path %></li>
          </ul>
        </span>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to t('navbar.satın_aldıklarım'), purchases_path %></li>
            <li><%= link_to t('navbar.profilini_düzenle'), edit_user_registration_path %></li>
            <li><%= link_to t('navbar.oturumu_kapat'), destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to t('navbar.Üye ol'), new_user_registration_path %></li>
        <li><%= link_to t('navbar.Üye Girişi'), new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Karlı Bebek</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>

<%= render "/layouts/facebook" %>	

<%= render "/layouts/header" %>
<div class="container">

	<% flash.each do |name, msg| %>
	 <% if msg.is_a?(String) %>
	  <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<%= content_tag :div, msg, :id  =>  "flash_#{name}" %>
	  </div>
	 <% end %>
	<% end %>

  <%= yield %>

<%= render "/layouts/footer" %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to Etsy demo</h1>
<h2>Etsydemo is an online marketplace for selling and buying goods</h2>

app/views/pages/contact.html.erb
<h1>Email us at abc@etsydemo.com</h1>